view/__init__.py
#!/usr/bin/python3
from flask import Blueprint

from .routes import views

view/app.py
#!/usr/bin/python3
from flask import Flask
from flask_cors import CORS
from view.routes import views
import os


myapp = Flask(__name__)
cors = CORS(myapp, resources={r"/*": {"origin": "*"}})

def create_myapp():
    """Initialize the flask myapp"""
    myapp.register_blueprint(views)
    return myapp


if __name__ == '__main__':
    port = int(os.getenv('PORT', 5000))
    host = os.getenv('HOST', '0.0.0.0')
    myapp = create_myapp()
    myapp.run(port=port, host=host)

view/routes.py
#!/usr/bin/python3
"""This is the views or routes for the website"""

from flask import Blueprint, render_template

views = Blueprint('views', __name__)

@views.route('/', strict_slashes=False, methods=['GET'])
def home_page():
    """Landing page"""
    return render_template('index.html')

@views.route('/login', strict_slashes=False, methods=['GET'])
def login():
    """Login page"""
    return render_template('login.html')


@views.route('/signup', strict_slashes=False, methods=['GET'])
def signup():
    """Signup page"""
    return render_template('signup.html')


@views.route('/home', strict_slashes=False, methods=['GET'])
def main():
    """home page of project"""
    return render_template('main.html')

view/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}" type="image/x-icon">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/header.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/footer.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/landing-page.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <style>
        .landing-page {
            background-image: url("{{ url_for('static', filename='images/screen.jpg') }}");
        }
    </style>
    <title>Rentopia</title>
</head>
<body>
    <header>
        <div class="logo">
            <img src="{{url_for('static', filename='images/Rentopia.png')}}" alt="">
        </div>
        <nav>
            <div class="upper-nav">
                <a href="{{ url_for('views.main') }}">VIEW HOMES</a>
                <a href="{{ url_for('views.signup') }}"><button class="signup">GET STARTED</button></a>
                <a href="{{ url_for('views.login') }}">LOGIN</a>
            </div>
        </nav>
    </header>
    <div class="landing-page">
        <h1>RenTopia... Rent made easy</h1>
        <div class="msg">
            <p>RENTOPIA allows you to easily locate houses available for rent. Save yourself from the hustle and scams! Find your new home from your old home.</p>
        <div class="reach">
            <p>Want to post your apartment available for rent?</p>
            <form action="view/routes.py" method="post">
                <input type="text" name="firstname" id="fname" placeholder="First Name" required>
                <input type="text" name="lastname" id="lname" placeholder="Last Name" required>
                <input type="email" name="email" id="username" placeholder="Email">
                <input type="tel" name="phone" id="telephone" placeholder="Telephone Number" required>
                <fieldset>
                    <legend>Apartment Information</legend>
                    <label for="Location">Where is your Apartment located?</label>
                    <select name="location" id="location" required>
                        <option value="Ashanti">Ashanti</option>
                        <option value="Bono">Bono</option>
                        <option value="Bono East">Bono East</option>
                        <option value="Ahafo">Ahafo</option>
                        <option value="Central">Central</option>
                        <option value="Eastern">Eastern</option>
                        <option value="Greater Accra">Greater Accra</option>
                        <option value="Nothern">Northen</option>
                        <option value="Savannah">Savannah</option>
                        <option value="North East">North East</option>
                        <option value="Upper East">Upper East</option>
                        <option value="Upper West">Upper West</option>
                        <option value="Oti">Oti</option>
                        <option value="Volta">Volta</option>
                        <option value="Western">Western</option>
                        <option value="Western North">Western North</option>
                    </select>
                    <label for="rooms">How many rooms are in your apartment?</label>
                    <input type="number" name="number" id="number" required>
                    <label for="message">Any other information you would like to let us know?</label>
                    <input type="text" name="extra" id="extra" placeholder="Tell us more...">
                </fieldset>
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
    <footer>
        <section id="bottom-nav">
            <ul>
                <li id="about">ABOUT US</li>
                <p>RenTopia is a User friendly website that aids people to find homes around them. Looking at the hustle involved in securing accomodation, we seek to make it easier to find homes around you and in different regions and cities. By creating an account with us, we present you with affordable and quality acommodations in any place of your choice in Ghana. 
                </p>
                <li id="contact">CONTACT OUR DEVELOPERS ON </li>
                <br>
                <div class="links">
                    <div class="repo">
                        <li>Repository</li>
                        <a href="https://github.com/angelotheman/RenTopia" target="_blank"><i class="fa fa-github" style="font-size:24px"></i></a>
                    </div>
                    <div class="accounts">
                        <li>Github</li>
                        <a href="https://github.com/ikuffourosei" target="_blank"><i class="fa fa-github" style="font-size:24px"></i></a></a>
                        <a href="https://github.com/angelotheman" target="_blank"><i class="fa fa-github" style="font-size:24px;color:red"></i></a></a>
                    </div>
                    <div class="repo">
                        <li>LinkedIn</li>
                        <a href="https://www.linkedin.com/in/kuffour-emmanuel-osei-a45313260/" target="_blank"><i class="fa fa-linkedin" style="font-size:24px"></i></a>
			<a href="https://www.linkedin.com/in/angelotheman/" target="_blank"><i class="fa fa-linkedin" style="font-size:24px"></i></a>

                    </div>
                </div>
            </ul>
        </section>
    </footer>
</body>
</html>

view/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}" type="image/x-icon">
    <title>login</title>
</head>
<body>
    <h1>Welcome to Login Page</h1>
</body>
</html>

view/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/signup.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/header.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}" type="image/x-icon">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Homes</title>
</head>
<body>
    <header>
        <div class="logo">
            <img src="{{url_for('static', filename='images/Rentopia.png')}}" alt="">
        </div>
    </header>
</body>
</html>

view/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/signup.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/header.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}" type="image/x-icon">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <style>
        body {
            background-image: url("{{ url_for('static', filename='images/screen.jpg')}}");
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>
    <title>signup</title>
</head>
<body>
    <header>
        <div class="logo">
            <img src="{{url_for('static', filename='images/Rentopia.png')}}" alt="">
        </div>
    </header>
    <div class="signup">
        <div class="forms">
            <h1>Signup Here</h1>
            <form class="row g-3">
                <div class="col-md-6">
                  <label for="inputname4" class="form-label">Name</label>
                  <input type="text" class="form-control" id="inputname4" required>
                </div>
                <div class="col-md-6">
                    <label for="inputemail4" class="form-label">Email</label>
                    <input type="text" class="form-control" id="inputemail4" required>
                </div>
                <div class="col-md-6">
                    <label for="inputphone4" class="form-label">Telephone</label>
                    <input type="tel" class="form-control" id="inputphone4" placeholder="02344...">
                </div>
                <div class="col-md-6">
                  <label for="inputPassword4" class="form-label">Password</label>
                  <input type="password" class="form-control" id="inputPassword4" required>
                </div>
                <div class="col-md-6">
                  <label for="inputPassword4" class="form-label">Confirm Password</label>
                  <input type="password" class="form-control" id="inputPassword4">
                </div>
                <div class="col-md-4">
                  <label for="inputState" class="form-label">Region</label>
                  <select id="inputState" class="form-select">
                        <option value="Ashanti">Ashanti</option>
                        <option value="Bono">Bono</option>
                        <option value="Bono East">Bono East</option>
                        <option value="Ahafo">Ahafo</option>
                        <option value="Central">Central</option>
                        <option value="Eastern">Eastern</option>
                        <option value="Greater Accra">Greater Accra</option>
                        <option value="Nothern">Northen</option>
                        <option value="Savannah">Savannah</option>
                        <option value="North East">North East</option>
                        <option value="Upper East">Upper East</option>
                        <option value="Upper West">Upper West</option>
                        <option value="Oti">Oti</option>
                        <option value="Volta">Volta</option>
                        <option value="Western">Western</option>
                        <option value="Western North">Western North</option>
                    </select>
                </div>
                <div class="col-12">
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                      <label class="form-check-label" for="invalidCheck">
                        Agree to terms and conditions
                      </label>
                      <div class="invalid-feedback">
                        You must agree before submitting.
                      </div>
                    </div>
                  </div>                
                <div class="col-12">
                  <button type="submit" class="btn btn-primary">Create Account</button>
                </div>
            </form>
</body>
</html>